version: "3.8"

services:
    mongodb:
        image: mongo:latest
        container_name: mongodb_container
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            MONGO_INITDB_DATABASE: mydatabase
        volumes:
            - mongodb_data:/data/db
        networks:
            - mongodb_network

volumes:
    mongodb_data:

networks:
    mongodb_network:
        driver: bridge
